# Generated by Django 5.0.14 on 2026-09-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado_venta', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('INACTIVA', 'Inactiva/Eliminada')], default='DISPONIBLE', max_length=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('UF', 'UF'), ('CLP', 'CLP')], default='UF', max_length=3)),
                ('superficie_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Superficie total (m²)')),
                ('habitaciones', models.PositiveSmallIntegerField(default=1)),
                ('banos', models.PositiveSmallIntegerField(default=1, verbose_name='Baños')),
                ('comuna', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('fotografia_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
