# Generated by Django 5.0.14 on 2026-09-23 23:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, 'El máximo permitido es 20 baños.')], verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='codigo_referencia',
            field=models.CharField(error_messages={'unique': 'Ya existe una propiedad con ese código de referencia.'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'El código debe tener al menos 3 caracteres.'), django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'El código solo puede contener letras, números y guiones (sin espacios).')], verbose_name='Código de referencia'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='comuna',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3, 'La comuna debe tener al menos 3 caracteres.'), django.core.validators.RegexValidator("^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s\\.\\-']+$", 'La comuna solo puede contener letras, espacios, puntos y guiones.')]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'La descripción debe tener al menos 20 caracteres.')], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'La dirección debe tener al menos 5 caracteres.')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado_venta',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('INACTIVA', 'Inactiva/Eliminada')], default='DISPONIBLE', max_length=12, verbose_name='Estado de venta'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fotografia_principal',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Fotografía principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50, 'El máximo permitido es 50 habitaciones.')]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'El precio debe ser mayor que cero.')], verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='superficie_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'La superficie debe ser mayor que cero.'), django.core.validators.MaxValueValidator(Decimal('100000'), 'La superficie no puede superar 100.000 m².')], verbose_name='Superficie total (m²)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5, 'El título debe tener al menos 5 caracteres.')], verbose_name='Título'),
        ),
    ]
