# Generated by Django 5.0.14 on 2026-10-08 00:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_propiedad_banos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Inmobiliario'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'La descripción debe tener al menos 20 caracteres.'), django.core.validators.MaxLengthValidator(800, 'La descripción no puede superar los 800 caracteres.')], verbose_name='Descripción'),
        ),
    ]
